apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-movie-catalog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OmriGM/NetflixInfra.git
    targetRevision: HEAD
    path: k8s/NetflixMovieCatalog
  destination:
    server: https://kubernetes.default.svc
    namespace: default
