apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
          {
            "version": 2,
            "name": "Redis",
            "type": "redis-datasource",
            "url": "<my-redis-service-url>",
            "isDefault": true
          }
        ]
    }
