apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
   server {
     listen 80;
     server_name  localhost;
     location / {
       proxy_pass http://netflix-frontend-service:3000;
      }
    } 